sudo: required

language: generic

services:
  - docker

before_install:
  - source version.sh
  - echo $VERSION
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -f latest/Dockerfile -t dgoodman/myrepo .
  - docker build -f slim/Dockerfile -t dgoodman/myrepo:slim .
  - docker tag dgoodman/myrepo dgoodman/myrepo:$VERSION
  - docker tag dgoodman/myrepo:slim dgoodman/myrepo:$VERSION-slim

script:
  - docker run -d dgoodman/myrepo:latest
  - docker ps | grep latest
  - docker run -d dgoodman/myrepo:slim
  - docker ps | grep slim

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -e "$DOCKER_EMAIL" -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push dgoodman/myrepo;
    fi